### ISSUE TITLE
Smooch.startConversation ();

### ISSUE THREAD

**Issue by marlonpcg** [smooch/smooch-web#682] opened 2019-12-24 15:28 UTC
What do I need to do to work Smooch.startConversation (); ? 
Is there any example? 
It does not work when I use it.

**Comment by DataWearsAHood** [comment] 2020-01-03 14:32
In general terms, Smooch.startConversation() is intended to be used to force the backend to create the appUser before the first message is sent, and also generate a `conversation:start` event, which you should listen for via webhook.

Please note, as mentioned in the link below, that using this functionality will incur an AUC charge for the current appUser+calendar month, even if no messages are exchanged with this web user.
* webSDK API docs: https://github.com/smooch/smooch-web#startconversation
* webhook trigger docs: https://docs.smooch.io/rest/#conversation-events

If you have further questions, you can reach out to our support team via the chat widget in your Sunshine Conversations dashboard.

**Comment by marlonpcg** [comment] 2020-01-03 14:44
Thanks @DataWearsAHood 

It is possible to create in Web Messenger some standard messages and buttons without including AUC charge?

**Comment by DataWearsAHood** [comment] 2020-01-13 14:13
Hello @marlonpcg,

Not at this time, but keep an eye out for our Proactive messages feature,  planned for release later in Q1-2020.

Since we've confirmed this is not a bug with Smooch.startConversation() or the repo, we'll be closing this GH issue.

**Closed** 2020-01-13 14:20 UTC
